---
- name: Backup Config
  hosts: R1
  gather_facts: false
  connection: local
 
  tasks:
   - name: Get running configuration
     ios_command:
       commands:
         - show running-config  
     register: config
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_run_{{ inventory_hostname }}.txt"
 
- name: Backup Config
  hosts: R2
  gather_facts: false
  connection: local
 
  tasks:
   - name: Get running configuration
     ios_command:
       commands:
         - show running-config  
     register: config
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_run_{{ inventory_hostname }}.txt"
